### ISSUE TITLE
Seeded random for graphs generation

### ISSUE THREAD

**Issue by jacomyal** [graphology/graphology-generators#5]
With @sim51, for the end-to-end testing of [sigma v2](https://github.com/jacomyal/sigma.js/tree/v2/test/e2e), we would like to be able to make reproducible our examples (like [this one](https://github.com/jacomyal/sigma.js/blob/v2/examples/custom-nodes.ts) for instance).

Is it possible to override the random generator used in the graphs generators?

**Comment by Yomguithereal** [comment]
It is already possible :). All those functions take a `rng` option so you do just that.
